# Generated by Django 5.2.5 on 2025-11-17 04:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('usuario', 'Usuario')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('refugio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdoptaUnaPatitaApp.refugio')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_adoptante', models.CharField(max_length=100)),
                ('correo_adoptante', models.EmailField(max_length=254)),
                ('mascota_id', models.IntegerField(blank=True, null=True)),
                ('mascota_nombre', models.CharField(blank=True, max_length=100)),
                ('comentarios', models.TextField(blank=True)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('mascota_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdoptaUnaPatitaApp.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('comentarios', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsable', models.CharField(max_length=100)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='AdoptaUnaPatitaApp.solicitud')),
            ],
        ),
    ]
