# Generated by Django 5.2.5 on 2025-11-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdoptaUnaPatitaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='estado',
        ),
        migrations.DeleteModel(
            name='Seguimiento',
        ),
    ]
