# Generated by Django 5.2.5 on 2025-11-17 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdoptaUnaPatitaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='refugio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdoptaUnaPatitaApp.refugio'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='mascota_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdoptaUnaPatitaApp.mascota'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='mascota_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdoptaUnaPatitaApp.mascota'),
        ),
    ]
