# Generated by Django 5.2.5 on 2025-10-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdoptaUnaPatitaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='correo_adoptante',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='mascota',
            field=models.CharField(max_length=100),
        ),
    ]
