# Generated by Django 5.2.5 on 2025-10-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdoptaUnaPatitaApp', '0002_solicitud_correo_adoptante_alter_solicitud_mascota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='correo_adoptante',
        ),
    ]
