# Generated by Django 5.2.5 on 2025-11-17 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdoptaUnaPatitaApp', '0002_remove_solicitud_comentarios_remove_solicitud_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='refugio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdoptaUnaPatitaApp.refugio'),
        ),
    ]
