# Generated by Django 5.2.7 on 2025-10-19 01:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdoptaUnaPatitaApp', '0003_remove_solicitud_correo_adoptante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='usuario',
            new_name='nombre_adoptante',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='correo_adoptante',
            field=models.EmailField(default='correo@ejemplo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdoptaUnaPatitaApp.mascota'),
        ),
    ]
